In [6]:
import numpy as np
mrks=np.array([[85,72,91,60,88],[3,33,3,33,5]])
print(mrks)
print(mrks.dtype)
print(mrks.shape)
print(mrks.ndim)

zeros=np.zeros(5)
ones=np.ones(5)
rng=np.arange(0,10,2)
linsp=np.linspace(0,1,5)
rnd=np.random.randint(50,100,size=6)
print(ones)
print(zeros)
print(rng)
print(linsp)
print(rnd)

[[85 72 91 60 88]
 [ 3 33  3 33  5]]
int64
(2, 5)
2
[1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0.]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[68 85 57 84 98 57]


In [12]:
scores=np.array([
    [85,72,91,60,88],
    [3,33,3,33,5],
    [45,55,65,75,85]
])
print(scores.shape)
print(scores.ndim)
print(scores.size)

eye=np.eye(3)
grid=np.zeros((3,3))
print(eye)
print(grid)

print("\n",scores[0,1])
print(scores[:,0])
print(scores[1,:])
print(scores[0:2,1:])

(3, 5)
2
15
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

 72
[85  3 45]
[ 3 33  3 33  5]
[[72 91 60 88]
 [33  3 33  5]]


In [14]:
mrks= np.array([85,72,91,60,8])
print(np.sqrt(mrks))
print(np.abs([-5, 0, -7]))
print(np.mean(mrks))
print(np.median(mrks))
print(np.std(mrks))
print(np.clip(mrks, 60, 90))
print(np.where(mrks < 70, "Fail", "Pass"))

[9.21954446 8.48528137 9.53939201 7.74596669 2.82842712]
[5 0 7]
63.2
72.0
29.606755985754333
[85 72 90 60 60]
['Pass' 'Pass' 'Pass' 'Fail' 'Fail']
